language: android

# use container based build infrastructure
sudo: false

jdk:
 - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew clean buildDebug check -PdisablePreDex

cache:
  directories:
    - $HOME/.gradle
